services:
  BDHSuiteCore:
    image: postgres:18.1
    container_name: BDHSuiteCore
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    networks:
      - BDHSuiteCore_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  BDHSuiteCore_network:

volumes:
  BDHSuiteCore_pgdata:
